### ISSUE TITLE
Why are the fields in DropwizardAwareModule declared as volatile?

### ISSUE THREAD

**Issue by jaredculp** [HubSpot/dropwizard-guicier#10]
Specifically: https://github.com/HubSpot/dropwizard-guicier/blob/master/src/main/java/com/hubspot/dropwizard/guicier/DropwizardAwareModule.java#L12-L14

**Comment by jhaber** [comment]
Realistically they probably don't need to be, but I was concerned about the thread visibility of writes to those fields. However, any example I can think of where this would be an issue is pretty contrived

**Comment by jaredculp** [comment]
Thanks for the quick response and explanation!
