### ISSUE TITLE
Expose injector for use in integration tests

### ISSUE THREAD

**Issue by jaredculp** [HubSpot/dropwizard-guicier#12]
Is there a way to set up an integration test environment with some combination of dropwizard's `DropwizardAppRule` that would expose the injector used to start the service, so that you could grab an instance of an object (say a Dao)?

**Comment by jhaber** [comment]
Hey Jared, thanks for the suggestion. I haven't used the dropwizard testing stuff in a while so I'll take a look and see how we can accommodate this use-case

**Comment by jaredculp** [comment]
Thanks for the response! I'm playing around with it too -- if I come up with something useful I'll submit a PR.

**Comment by jaredculp** [comment]
Would storing the injector to an instance variable [here](https://github.com/HubSpot/dropwizard-guicier/blob/master/src/main/java/com/hubspot/dropwizard/guicier/GuiceBundle.java#L78) and exposing it as a getter be reasonable?

**Comment by jaredculp** [comment]
@jhaber I see that the injector was previously exposed in the older version of this lib: https://github.com/HubSpot/dropwizard-guice/blob/master/src/main/java/com/hubspot/dropwizard/guice/GuiceBundle.java#L145-L148. Any reason why that was dropped?

**Comment by jaredculp** [comment]
Ping @jhaber any update on this?

**Comment by jaredculp** [comment]
I put together a pr here: https://github.com/HubSpot/dropwizard-guicier/pull/15

**Comment by huangyq23** [comment]
@jhaber did you get a chance to take a look at #15?
It is an important use case for us and we would like to avoid creating a fork.
