### ISSUE TITLE
support dropwizard 1.0.4 

### ISSUE THREAD

**Issue by lifey** [HubSpot/dropwizard-guicier#16]
Current version of guicier does not support dropwizard 1.0.4 (conflict on org.glassfish.hk2:hk2-api) 
Is it possible to solve it ?

**Comment by jhaber** [comment]
Hi Haim, thanks for the issue. I just released dropwizard-guicier 1.0.6.0 which uses dropwizard 1.0.6. It should show up in Maven central soon
