### ISSUE TITLE
relationship with dropwizard-guice

### ISSUE THREAD

**Issue by Jimexist** [HubSpot/dropwizard-guicier#20]
What's the relationship between this repo and `dropwizard-guice`? I can see that most recent updates went into this repo. Thanks.

**Comment by jhaber** [comment]
Hi Jiayu, I would say that this is a successor to and improvement on dropwizard-guice. The changes are too fundamental to merge into dropwizard-guice so we made a new project. We will still be maintaining dropwizard-guice, but internally our projects are migrating to dropwizard-guicier. I can try to document the design differences more clearly in the READMEs if you think it would be helpful

**Comment by Jimexist** [comment]
@jhaber thanks for the info - we are using `dropwizard-guice` and think it is wonderful. However the tiny discrepancy between jersey/hk2 versions is creating conflict issues. We are looking forward to this repo being the solution to the problem. So if this is the way to go we are happy to migrate and/or also help to contribute.

**Comment by jhaber** [comment]
I added a note to dropwizard-guice README suggesting that new development using dropwizard-guicier:
https://github.com/HubSpot/dropwizard-guice#note
