### ISSUE TITLE
dropwizard-guicier has no license

### ISSUE THREAD

**Issue by andy-paine** [HubSpot/dropwizard-guicier#34]
There is no license to guide usage of dropwizard-guicier. dropwizard-guice does have an [Apache license](https://github.com/HubSpot/dropwizard-guice/blob/master/LICENSE.txt) which seems appropriate

**Comment by kmclarnon** [comment]
Resolved by https://github.com/HubSpot/dropwizard-guicier/pull/35

**Comment by kmclarnon** [comment]
Thanks for pointing that out 👍
