### ISSUE TITLE
upgrade jersey

### ISSUE THREAD

**Issue by devinrsmith** [HubSpot/dropwizard-guicier#4]
This library conflicts with newer dropwizard versions that use jersey 2.x.

I'm considering switching over from https://github.com/HubSpot/dropwizard-guice (which doesn't have this same issue), but no able to in the current state.

**Comment by jhaber** [comment]
Hey Devin, thanks for the issue! This is definitely something we plan on tackling in the near future

**Comment by devinrsmith** [comment]
Glad to hear, thanks for the response. Looking forward to checking back in the future.

**Comment by jhaber** [comment]
I just released version 0.9.1.0 which uses dropwizard 0.9.1 and jersey 2.22.1, let me know if you run into any issues!
