### ISSUE TITLE
Where can I find dropwizard-guicier to dropwizard compatibility info?

### ISSUE THREAD

**Issue by bharathguvvala** [HubSpot/dropwizard-guicier#53]
I see that the release notes for dropwizard-guicier doesn't contain the compatibility information with dropwizard. Where can I get that information from? It'd come handy when debugging dependency related issues.

**Comment by bharathguvvala** [comment]
Are the versions of dropwizard-guicier same as the dropwizard it supports?

**Comment by jhaber** [comment]
Correct, dropwizard-guicier `a.b.c.d` was meant to work with dropwizard version `a.b.c`

**Comment by bharathguvvala** [comment]
I don't see a release for 0.8.x , is that not supported?

**Comment by jhaber** [comment]
Unfortunately this library jumped straight from 0.7.x to 0.9.x
