### ISSUE TITLE
ConcurrentModificationException at application start

### ISSUE THREAD

**Issue by hexwit** [HubSpot/dropwizard-guicier#7]
I am initialising application as following: 

```
GuiceBundle<HelloWorldConfiguration> guiceBundle = GuiceBundle.defaultBuilder(HelloWorldConfiguration.class)
                .modules(new HibernateModule(bootstrap))
                .build();

bootstrap.addBundle(guiceBundle);
```

```
public class HibernateModule extends DropwizardAwareModule<HelloWorldConfiguration> {
    public HibernateModule(Bootstrap<HelloWorldConfiguration> bootstrap) {
        //bootstrap.addBundle(new MyHibernateBundle()); // <-- this works.
    }

    @Override
    public void configure(Binder binder) {
        //Can't use MyHibernateBundle here. Compiler will complain.
        ConfiguredBundle bundle = new MyHibernateBundle();
        getBootstrap().addBundle(bundle);
    }

    private class MyHibernateBundle extends HibernateBundle<HelloWorldConfiguration> {
        public MyHibernateBundle() {
            super(Person.class);
        }

        @Override
        public PooledDataSourceFactory getDataSourceFactory(HelloWorldConfiguration configuration) {
            return configuration.getDataSourceFactory();
        }
    }
}
```

If i use getBootstrap() method in configure() then I will have following exception: 

```
Exception in thread "main" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:196)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:79)
```

If I will use constructor parameter - it is working.
Beside this getBootstrap().addBundle() can't accept specific class and i have to pass 
parent one, and skip type checking to able to compile code.

Could you check and tell where is the issue, and why I can't use getBootstrap()?

**Comment by jhaber** [comment]
The issue is that the Guice injector gets created during the run phase, so you're trying to add a bundle to the bootstrap too late. Bundles need to be added during the initialize phase (which is what happens if you do it eagerly in the constructor). During the run phase, the bootstrap is already looping over all the bundles and running them:

```java
        for (ConfiguredBundle<? super T> bundle : configuredBundles) {
            bundle.run(configuration, environment);
        }
```

So the bootstrap is running the dropwizard-guicier bundle and it tries to add a new bundle, hence the `ConcurrentModificationException`

**Comment by jhaber** [comment]
Unfortunately this is a limitation of dropwizard-guicier, the alternative is to build the injector during the initialize phase but we took that approach in [dropwizard-guice](https://github.com/HubSpot/dropwizard-guice) and it has significant disadvantages
